"""Generate ``docs/sample_qa.md`` from real runs of the built system.

The deliverable is "real build output", so this file is the thing that produces it. Writing
the Q&A document by hand would be the same category of error as hand-typing a scheme fact:
it would drift from the code on the first change and nobody would notice until a reviewer ran
the app and got different numbers.

Every block below is captured from :func:`answer_question`, unedited. Re-run with
``python tools/make_sample_qa.py`` after any change to retrieval, chunking or the guards.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from mf_rag.answerer import answer_question  # noqa: E402
from mf_rag.config import settings  # noqa: E402

# Six scheme facts, three concept/procedural, four refusals. The refusals are in the document
# on purpose: a facts-only bot is defined as much by what it declines as by what it answers,
# and a sample Q&A that only shows successes is an advertisement rather than evidence.
FACTUAL = [
    "What is the expense ratio of HDFC Large Cap Fund Direct Growth?",
    "What is the exit load of HDFC Large Cap Fund Direct Growth?",
    "What is the minimum SIP investment for HDFC Small Cap Fund?",
    "What is the lock-in period of HDFC ELSS Tax Saver?",
    "What benchmark does HDFC Flexi Cap Fund track?",
    "What is the riskometer level of HDFC Balanced Advantage Fund?",
    "How do I download the factsheet for HDFC Large Cap Fund?",
    "What is the exit load of HDFC Small Cap Fund?",
]

CONCEPT = [
    "What is the difference between ELSS and SIP?",
    "What does riskometer mean?",
    "Is stamp duty charged on mutual fund investments?",
]

REFUSALS = [
    "Should I buy HDFC Small Cap Fund?",
    "Which HDFC fund has the highest returns?",
    "Is HDFC Flexi Cap a good investment?",
    "What is my PAN number for KYC?",
]


def _block(question: str) -> str:
    answer = answer_question(question)
    out = [f"### `{question}`", ""]
    out.append(f"**Mode:** `{answer.mode}`" + (f" · guard `{answer.guard}`" if answer.guard else ""))
    out.append("")
    out.append("> " + answer.text.replace("\n", "\n> "))
    out.append("")
    if answer.citations:
        out.append(f"**Source:** {answer.citations[0]}")
    else:
        out.append("**Source:** none — this is a refusal, not a fact.")
    out.append("")
    if answer.notes:
        out.append("<details><summary>Why</summary>")
        out.append("")
        for note in answer.notes:
            out.append(f"- {note}")
        out.append("")
        out.append("</details>")
        out.append("")
    return "\n".join(out)


def main() -> None:
    llm = "llm" if settings.groq_api_key else "extractive (deterministic fallback)"
    parts = [
        "# Sample Q&A",
        "",
        f"Generated by `python tools/make_sample_qa.py` on {date.today().isoformat()}.",
        "",
        f"Answer path exercised: **{llm}**.",
        "",
        "This file is generated, not written by hand. Every answer below is the actual output of",
        "`answer_question()` on the built index, including the refusals.",
        "",
        "---",
        "",
        "## Scheme facts",
        "",
    ]
    for q in FACTUAL:
        parts.append(_block(q))

    parts += ["---", "", "## Concept and procedural questions", ""]
    for q in CONCEPT:
        parts.append(_block(q))

    parts += ["---", "", "## Refusals", ""]
    for q in REFUSALS:
        parts.append(_block(q))

    out = ROOT / "docs" / "sample_qa.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out} ({len(FACTUAL) + len(CONCEPT) + len(REFUSALS)} questions)")


if __name__ == "__main__":
    main()
